### **DATA CLEANING AND PREPROCESSING PROJECT** <br> *Project Level: Beginner <br> Data Source: 365-DataScience Absenteeism-Data*
#### **OBJECTIVE:**<br>A reputable firm has collected a fairly cleaned data on their employees' absence from work during normal working hours, resulting <br>in temporary incapacity to execute regular working activities. As a Data Analyst, I am tasked to ensure that the raw dataset, as was <br> collected, has been turned into a meaningful quantitative information for modelling and prescriptive analytics in Python.

#### **Importing Libraries and Loading Dataset**

In [534]:
import numpy as np
import pandas as pd

In [535]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [536]:
raw_data =  pd.read_csv("Absenteeism-data.csv")

df = raw_data.copy()
print(f"Shape of the DataFrame:\n{df.shape}\n")
df.head()

Shape of the DataFrame:
(700, 12)

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2

#### **Inspecting Dataset**

In [537]:
print(df.info(), '\n')

df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         700 non-null    int64
 1   Reason for Absence         700 non-null    int64
 2   Date                       700 non-null    object
 3   Transportation Expense     700 non-null    int64
 4   Distance to Work           700 non-null    int64
 5   Age                        700 non-null    int64
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64
 8   Education                  700 non-null    int64
 9   Children                   700 non-null    int64
 10  Pets                       700 non-null    int64
 11  Absenteeism Time in Hours  700 non-null    int64
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB
None

,ID,Reason for Absence,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
count,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000
mean,17.951429,19.411429,222.347143,29.892857,36.417143,271.801774,26.737143,1.282857,1.021429,0.687143,6.761429
std,11.028144,8.356292,66.312960,14.804446,6.379083,40.021804,4.254701,0.668090,1.112215,1.166095,12.670082
min,1.000000,0.000000,118.000000,5.000000,27.000000,205.917000,19.000000,1.000000,0.000000,0.000000,0.000000
25%,9.000000,13.000000,179.000000,16.000000,31.000000,241.476000,24.000000,1.000000,0.000000,0.000000,2.000000
50%,18.000000,23.000000,225.000000,26.000000,37.000000,264.249000,25.000000,1.000000,1.000000,0.000000,3.000000
75%,28.000000,27.000000,260.000000,50.000000,40.000000,294.217000,31.000000,1.000000,2.000000,1.000000,8.000000
max,36.000000,28.000000,388.000000,52.000000,58.000000,378.884000,38.000000,4.000000,4.000000,8.000000,120.000000

#### **ID**

In [538]:
## Dropping the nominal column [ID] to make room for direct overarching quatitative analysis
df = df.drop(['ID'], axis = 1)
df.head()

,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23,23/07/2015,289,36,33,239.554,30,1,2,1,2

#### **Reason for Absence**

In [539]:
## Column Values:
print(f"Reason for Absence:\n{df['Reason for Absence'].tolist()}\n")
## Min & Max Values
print(f"Max_Value:\n{df['Reason for Absence'].max()}\n\nMin_Value:\n{df['Reason for Absence'].min()}\n")
## Unique Values
print(f"Sorted Unique Values:\n{np.sort(pd.unique(df['Reason for Absence']))}\n\nNumber of Unique Values:\n{df['Reason for Absence'].nunique()}")

Reason for Absence:
[26, 0, 23, 7, 23, 23, 22, 23, 19, 22, 1, 1, 11, 11, 23, 14, 23, 21, 11, 23, 10, 11, 13, 28, 18, 25, 23, 28, 18, 23, 18, 18, 23, 18, 23, 23, 24, 11, 28, 23, 23, 23, 23, 19, 23, 23, 23, 23, 22, 14, 0, 0, 23, 23, 0, 0, 18, 23, 0, 23, 23, 23, 23, 23, 0, 23, 23, 23, 23, 23, 23, 23, 23, 23, 19, 14, 28, 26, 23, 28, 23, 23, 13, 21, 23, 10, 22, 14, 23, 6, 23, 21, 13, 28, 28, 28, 7, 23, 23, 19, 23, 26, 23, 26, 19, 22, 28, 28, 23, 22, 27, 19, 23, 23, 19, 27, 18, 27, 23, 28, 27, 27, 27, 27, 27, 27, 27, 27, 27, 18, 18, 27, 23, 27, 27, 23, 22, 23, 1, 11, 28, 23, 28, 22, 11, 1, 28, 23, 23, 23, 25, 18, 23, 23, 19, 28, 19, 19, 17, 22, 13, 13, 14, 13, 11, 1, 26, 13, 6, 8, 28, 23, 14, 13, 23, 11, 13, 11, 11, 13, 14, 28, 14, 28, 28, 23, 28, 13, 23, 28, 28, 13, 23, 23, 14, 28, 28, 19, 19, 12, 19, 13, 7, 0, 13, 28, 28, 18, 19, 7, 28, 12, 13, 0, 0, 0, 0, 11, 13, 22, 19, 22, 10, 23, 10, 11, 23, 10, 13, 13, 23, 13, 22, 11, 28, 28, 19, 1, 5, 26, 26, 18, 25, 1, 1, 25, 22, 26, 26, 19, 19, 0, 19, 19, 23, 18, 13, 14, 28, 23, 23, 11, 23, 13, 25, 23, 23, 19, 8, 6, 11, 23, 19, 0, 9, 28, 0, 0, 13, 9, 23, 28, 28, 26, 28, 0, 28, 7, 13, 24, 26, 26, 22, 0, 0, 1, 7, 22, 28, 1, 0, 19, 28, 0, 23, 23, 28, 28, 23, 28, 10, 0, 0, 0, 1, 7, 23, 11, 23, 6, 28, 23, 1, 11, 26, 0, 18, 11, 25, 28, 13, 12, 13, 28, 10, 15, 0, 0, 23, 12, 28, 28, 23, 28, 28, 4, 28, 28, 23, 25, 25, 28, 13, 14, 26, 28, 28, 19, 23, 19, 23, 13, 23, 26, 3, 26, 26, 28, 28, 28, 27, 7, 22, 28, 23, 27, 27, 10, 26, 27, 22, 27, 23, 23, 11, 27, 27, 10, 27, 27, 18, 19, 28, 28, 28, 22, 22, 22, 28, 22, 0, 21, 23, 14, 13, 0, 0, 0, 28, 22, 19, 28, 28, 28, 26, 22, 26, 23, 28, 23, 13, 28, 28, 28, 11, 13, 23, 10, 23, 28, 23, 28, 11, 8, 18, 25, 13, 25, 28, 1, 23, 23, 28, 28, 23, 28, 0, 13, 28, 28, 28, 26, 28, 23, 23, 5, 21, 28, 11, 13, 23, 25, 13, 7, 25, 26, 26, 28, 15, 23, 28, 9, 28, 23, 22, 22, 26, 28, 28, 23, 25, 25, 28, 28, 26, 26, 28, 25, 25, 23, 23, 28, 28, 28, 28, 28, 28, 28, 23, 28, 23, 23, 23, 23, 23, 23, 22, 4, 11, 26, 14, 28, 23, 23, 23, 23, 23, 23, 23, 26, 28, 1, 23, 10, 13, 10, 10, 23, 6, 10, 0, 13, 21, 28, 2, 28, 9, 24, 1, 23, 22, 28, 13, 14, 28, 23, 8, 23, 0, 0, 14, 0, 23, 26, 28, 13, 28, 23, 13, 23, 23, 14, 18, 26, 18, 13, 23, 23, 23, 18, 12, 12, 25, 25, 13, 25, 10, 18, 27, 18, 27, 27, 13, 27, 27, 13, 23, 1, 27, 28, 27, 27, 28, 27, 19, 27, 7, 27, 27, 25, 13, 23, 27, 12, 27, 27, 13, 27, 25, 25, 27, 7, 27, 23, 25, 27, 27, 25, 27, 23, 25, 25, 12, 27, 27, 27, 25, 27, 25, 19, 13, 27, 27, 27, 10, 13, 27, 7, 27, 23, 25, 27, 23, 27, 23, 27, 27, 23, 13, 27, 27, 13, 19, 22, 13, 10, 19, 19, 13, 27, 7, 16, 23, 23, 10, 22, 27, 19, 16, 27, 28, 19, 14, 27, 22, 19, 28, 8, 26, 13, 28, 14, 19, 22, 27, 23, 5, 28, 0, 27, 0, 16, 10, 10, 22, 10, 6, 10, 23, 28]

Max_Value:
28

Min_Value:
0

Sorted Unique Values:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 21 22 23 24
 25 26 27 28]

Number of Unique Values:
28

In [540]:
reason_columns = pd.get_dummies(df['Reason for Absence'], dtype= int)
reason_columns.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0

In [541]:
## Creating a [check] column to check the data integrity of the dummy variables 
reason_columns['check'] = reason_columns.sum(axis = 1)
reason_columns.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28,check
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
3,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1

In [542]:
## Checking the uniqueness of the dummy variables
print(pd.unique(reason_columns.check))
reason_columns['check'].sum(axis = 0)

[1]

np.int64(700)

In [543]:
## Dropping the [check] column after validating the data integrity of the dummy variables
reason_columns = reason_columns.drop(['check'], axis = 1)

reason_columns.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0

In [544]:
## Dropping the first column of the dummy variable (all zeroes) to avoid potential multicollinearity
reason_columns = pd.get_dummies(df['Reason for Absence'], drop_first = True)
reason_columns.head(10)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False

#### **Grouping Reasons for Absence**

In [545]:
print(df.columns.values, '\n')
print(reason_columns.columns.values)

['Reason for Absence' 'Date' 'Transportation Expense' 'Distance to Work'
 'Age' 'Daily Work Load Average' 'Body Mass Index' 'Education' 'Children'
 'Pets' 'Absenteeism Time in Hours']

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 21 22 23 24 25
 26 27 28]

In [546]:
df = df.drop(['Reason for Absence'], axis = 1)
df.head(10)

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23/07/2015,289,36,33,239.554,30,1,2,1,2
5,10/07/2015,179,51,38,239.554,31,1,0,0,2
6,17/07/2015,361,52,28,239.554,27,1,1,4,8
7,24/07/2015,260,50,36,239.554,23,1,4,0,4
8,06/07/2015,155,12,34,239.554,25,1,2,0,40
9,13/07/2015,235,11,37,239.554,29,3,1,1,8

In [547]:
## Generating groups from the 'reason_columns'
reason_type_1 = reason_columns.loc[:,1:14].max(axis = 1).astype(int)
reason_type_2 = reason_columns.loc[:,15:17].max(axis = 1).astype(int)
reason_type_3 = reason_columns.loc[:,18:21].max(axis = 1).astype(int)
reason_type_4 = reason_columns.loc[:,22:].max(axis = 1).astype(int)

reason_type_1

0      0
1      0
2      0
3      1
4      0
5      0
6      0
7      0
8      0
9      0
10     1
11     1
12     1
13     1
14     0
15     1
16     0
17     0
18     1
19     0
20     1
21     1
22     1
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     1
38     0
39     0
40     0
41     0
42     0
43     0
44     0
45     0
46     0
47     0
48     0
49     1
50     0
51     0
52     0
53     0
54     0
55     0
56     0
57     0
58     0
59     0
60     0
61     0
62     0
63     0
64     0
65     0
66     0
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     1
76     0
77     0
78     0
79     0
80     0
81     0
82     1
83     0
84     0
85     1
86     0
87     1
88     0
89     1
90     0
91     0
92     1
93     0
94     0
95     0
96     1
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
111    0
112    0
113    0
114    0
115    0
116    0
117    0
118    0
119    0
120    0
121    0
122    0
123    0
124    0
125    0
126    0
127    0
128    0
129    0
130    0
131    0
132    0
133    0
134    0
135    0
136    0
137    0
138    1
139    1
140    0
141    0
142    0
143    0
144    1
145    1
146    0
147    0
148    0
149    0
150    0
151    0
152    0
153    0
154    0
155    0
156    0
157    0
158    0
159    0
160    1
161    1
162    1
163    1
164    1
165    1
166    0
167    1
168    1
169    1
170    0
171    0
172    1
173    1
174    0
175    1
176    1
177    1
178    1
179    1
180    1
181    0
182    1
183    0
184    0
185    0
186    0
187    1
188    0
189    0
190    0
191    1
192    0
193    0
194    1
195    0
196    0
197    0
198    0
199    1
200    0
201    1
202    1
203    0
204    1
205    0
206    0
207    0
208    0
209    1
210    0
211    1
212    1
213    0
214    0
215    0
216    0
217    1
218    1
219    0
220    0
221    0
222    1
223    0
224    1
225    1
226    0
227    1
228    1
229    1
230    0
231    1
232    0
233    1
234    0
235    0
236    0
237    1
238    1
239    0
240    0
241    0
242    0
243    1
244    1
245    0
246    0
247    0
248    0
249    0
250    0
251    0
252    0
253    0
254    0
255    0
256    1
257    1
258    0
259    0
260    0
261    1
262    0
263    1
264    0
265    0
266    0
267    0
268    1
269    1
270    1
271    0
272    0
273    0
274    1
275    0
276    0
277    0
278    1
279    1
280    0
281    0
282    0
283    0
284    0
285    0
286    0
287    1
288    1
289    0
290    0
291    0
292    0
293    0
294    0
295    1
296    1
297    0
298    0
299    1
300    0
301    0
302    0
303    0
304    0
305    0
306    0
307    0
308    0
309    0
310    1
311    0
312    0
313    0
314    1
315    1
316    0
317    1
318    0
319    1
320    0
321    0
322    1
323    1
324    0
325    0
326    0
327    1
328    0
329    0
330    1
331    1
332    1
333    0
334    1
335    0
336    0
337    0
338    0
339    1
340    0
341    0
342    0
343    0
344    0
345    1
346    0
347    0
348    0
349    0
350    0
351    0
352    1
353    1
354    0
355    0
356    0
357    0
358    0
359    0
360    0
361    1
362    0
363    0
364    1
365    0
366    0
367    0
368    0
369    0
370    0
371    1
372    0
373    0
374    0
375    0
376    0
377    1
378    0
379    0
380    0
381    0
382    0
383    0
384    1
385    0
386    0
387    1
388    0
389    0
390    0
391    0
392    0
393    0
394    0
395    0
396    0
397    0
398    0
399    0
400    0
401    0
402    0
403    1
404    1
405    0
406    0
407    0
408    0
409    0
410    0
411    0
412    0
413    0
414    0
415    0
416    0
417    0
418    0
419    0
420    1
421    0
422    0
423    0
424    1
425    1
426    0
427    1
428    0
429    0
430    0
431    0
432    1
433    1
434    0
435    0
436    1
437    0
438    0
439    1
440    0
441    0
442    0
443    0
444    0
445    0
446    0
447    1
448    0
449    0
450    0
451    0
452    0
453    0
454    0
455    1
456    0
457    0
458    1
459    1
460    0
461    0
462    1
463    1
464    0
465    0
466    0
467    0
468    0
469    0
470    0
471    1
472    0
473    0
474    0
475    0
476    0
477    0
478    0
479    0
480    0
481    0
482    0
483    0
484    0
485    0
486    0
487    0
488    0
489    0
490    0
491    0
492    0
493    0
494    0
495    0
496    0
497    0
498    0
499    0
500    0
501    0
502    0
503    0
504    0
505    0
506    0
507    1
508    1
509    0
510    1
511    0
512    0
513    0
514    0
515    0
516    0
517    0
518    0
519    0
520    0
521    1
522    0
523    1
524    1
525    1
526    1
527    0
528    1
529    1
530    0
531    1
532    0
533    0
534    1
535    0
536    1
537    0
538    1
539    0
540    0
541    0
542    1
543    1
544    0
545    0
546    1
547    0
548    0
549    0
550    1
551    0
552    0
553    0
554    0
555    1
556    0
557    0
558    1
559    0
560    0
561    1
562    0
563    0
564    0
565    1
566    0
567    0
568    0
569    0
570    1
571    1
572    0
573    0
574    1
575    0
576    1
577    0
578    0
579    0
580    0
581    0
582    1
583    0
584    0
585    1
586    0
587    1
588    0
589    0
590    0
591    0
592    0
593    0
594    0
595    0
596    1
597    0
598    0
599    0
600    1
601    0
602    0
603    1
604    0
605    0
606    1
607    0
608    0
609    0
610    0
611    1
612    0
613    0
614    0
615    0
616    0
617    0
618    0
619    0
620    0
621    0
622    1
623    0
624    0
625    0
626    0
627    0
628    0
629    0
630    1
631    0
632    0
633    0
634    1
635    1
636    0
637    1
638    0
639    0
640    0
641    0
642    0
643    0
644    0
645    0
646    0
647    0
648    1
649    0
650    0
651    1
652    0
653    0
654    1
655    1
656    0
657    0
658    1
659    0
660    1
661    0
662    0
663    0
664    1
665    0
666    0
667    0
668    0
669    0
670    0
671    0
672    1
673    0
674    0
675    0
676    0
677    1
678    0
679    1
680    0
681    1
682    0
683    0
684    0
685    0
686    1
687    0
688    0
689    0
690    0
691    0
692    1
693    1
694    0
695    1
696    1
697    1
698    0
699    0
dtype: int64

#### **Concatenate Column Values**

In [548]:
## Adding the [Reason for Absence] column back to the dataframe
df = pd.concat([df, reason_type_1, reason_type_2, reason_type_3, reason_type_4], axis = 1)
df.head(10)

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,0,1,2,3
0,07/07/2015,289,36,33,239.554,30,1,2,1,4,0,0,0,1
1,14/07/2015,118,13,50,239.554,31,1,1,0,0,0,0,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2,0,0,0,1
3,16/07/2015,279,5,39,239.554,24,1,2,0,4,1,0,0,0
4,23/07/2015,289,36,33,239.554,30,1,2,1,2,0,0,0,1
5,10/07/2015,179,51,38,239.554,31,1,0,0,2,0,0,0,1
6,17/07/2015,361,52,28,239.554,27,1,1,4,8,0,0,0,1
7,24/07/2015,260,50,36,239.554,23,1,4,0,4,0,0,0,1
8,06/07/2015,155,12,34,239.554,25,1,2,0,40,0,0,1,0
9,13/07/2015,235,11,37,239.554,29,3,1,1,8,0,0,0,1

In [549]:
## Checking new column names 
df.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [550]:
## Changing column names to make [0,1,2,3] more meaningful
columns_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
                  'Daily Work Load Average', 'Body Mass Index', 'Education',
                  'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1', 
                  'Reason_2', 'Reason_3', 'Reason_4']

df.columns  = columns_names
df.head()

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Reason_1,Reason_2,Reason_3,Reason_4
0,07/07/2015,289,36,33,239.554,30,1,2,1,4,0,0,0,1
1,14/07/2015,118,13,50,239.554,31,1,1,0,0,0,0,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2,0,0,0,1
3,16/07/2015,279,5,39,239.554,24,1,2,0,4,1,0,0,0
4,23/07/2015,289,36,33,239.554,30,1,2,1,2,0,0,0,1

#### **Reorder Columns in DataFrame**

In [551]:
column_names_reordered = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Date', 'Transportation Expense', 
                          'Distance to Work', 'Age','Daily Work Load Average', 'Body Mass Index', 
                          'Education','Children', 'Pets', 'Absenteeism Time in Hours']

df = df[column_names_reordered]
df.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [552]:
## Checkpoint
df_reason_mode = df.copy()
df_reason_mode.head(10)

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,23/07/2015,289,36,33,239.554,30,1,2,1,2
5,0,0,0,1,10/07/2015,179,51,38,239.554,31,1,0,0,2
6,0,0,0,1,17/07/2015,361,52,28,239.554,27,1,1,4,8
7,0,0,0,1,24/07/2015,260,50,36,239.554,23,1,4,0,4
8,0,0,1,0,06/07/2015,155,12,34,239.554,25,1,2,0,40
9,0,0,0,1,13/07/2015,235,11,37,239.554,29,3,1,1,8

#### **Date**

In [553]:
df_reason_mode['Date'].head(10)

0    07/07/2015
1    14/07/2015
2    15/07/2015
3    16/07/2015
4    23/07/2015
5    10/07/2015
6    17/07/2015
7    24/07/2015
8    06/07/2015
9    13/07/2015
Name: Date, dtype: object

In [554]:
## Checking original datatype of the [Date] column
print(type(df_reason_mode['Date']))
print(df_reason_mode.Date.dtype)
print(type(df_reason_mode['Date'][0]))
print(type(df_reason_mode.Date[0]))

## Converting the [Date] column from 'str' to a timestamp,'pd.to_datetime()
df_reason_mode['Date'] = pd.to_datetime(df_reason_mode['Date'], format = '%d/%m/%Y')

## Checking data type after conversion
print(type(df_reason_mode.Date[0])) 
df_reason_mode.Date

<class 'pandas.core.series.Series'>
object
<class 'str'>
<class 'str'>
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

0     2015-07-07
1     2015-07-14
2     2015-07-15
3     2015-07-16
4     2015-07-23
5     2015-07-10
6     2015-07-17
7     2015-07-24
8     2015-07-06
9     2015-07-13
10    2015-07-20
11    2015-07-14
12    2015-07-15
13    2015-07-15
14    2015-07-15
15    2015-07-17
16    2015-07-17
17    2015-07-27
18    2015-07-30
19    2015-08-05
20    2015-08-12
21    2015-08-03
22    2015-08-10
23    2015-08-14
24    2015-08-17
25    2015-08-24
26    2015-08-04
27    2015-08-12
28    2015-08-19
29    2015-08-28
30    2015-08-17
31    2015-08-27
32    2015-08-27
33    2015-08-17
34    2015-08-17
35    2015-08-17
36    2015-08-04
37    2015-08-20
38    2015-08-21
39    2015-08-28
40    2015-09-01
41    2015-09-07
42    2015-09-01
43    2015-09-08
44    2015-09-09
45    2015-09-13
46    2015-09-14
47    2015-09-24
48    2015-09-04
49    2015-09-14
50    2015-09-21
51    2015-09-28
52    2015-09-08
53    2015-09-15
54    2015-09-22
55    2015-09-29
56    2015-09-16
57    2015-09-23
58    2015-09-30
59    2015-09-11
60    2015-09-18
61    2015-09-25
62    2015-10-06
63    2015-10-13
64    2015-10-14
65    2015-10-15
66    2015-10-16
67    2015-10-16
68    2015-10-06
69    2015-10-14
70    2015-10-21
71    2015-10-22
72    2015-10-21
73    2015-10-21
74    2015-10-22
75    2015-10-13
76    2015-10-20
77    2015-10-21
78    2015-10-23
79    2015-10-30
80    2015-11-05
81    2015-11-04
82    2015-11-05
83    2015-11-12
84    2015-11-19
85    2015-11-02
86    2015-11-09
87    2015-11-16
88    2015-11-18
89    2015-11-20
90    2015-11-18
91    2015-11-25
92    2015-11-20
93    2015-11-27
94    2015-11-02
95    2015-11-10
96    2015-11-11
97    2015-11-26
98    2015-12-01
99    2015-12-01
100   2015-12-02
101   2015-12-02
102   2015-12-03
103   2015-12-04
104   2015-12-08
105   2015-12-09
106   2015-12-10
107   2015-12-11
108   2015-12-15
109   2015-12-16
110   2015-12-11
111   2015-12-18
112   2015-12-18
113   2016-01-06
114   2016-01-04
115   2016-01-05
116   2016-01-05
117   2016-01-06
118   2016-01-07
119   2016-01-07
120   2016-01-08
121   2016-01-11
122   2016-01-12
123   2016-01-12
124   2016-01-13
125   2016-01-14
126   2016-01-15
127   2016-01-11
128   2016-01-12
129   2016-01-12
130   2016-01-12
131   2016-01-13
132   2016-01-21
133   2016-01-28
134   2016-01-25
135   2016-01-26
136   2016-01-28
137   2016-02-05
138   2016-02-03
139   2016-02-10
140   2016-02-11
141   2016-02-11
142   2016-02-12
143   2016-02-12
144   2016-02-08
145   2016-02-09
146   2016-02-15
147   2016-02-09
148   2016-02-16
149   2016-02-23
150   2016-02-25
151   2016-02-15
152   2016-02-16
153   2016-02-17
154   2016-02-25
155   2016-03-01
156   2016-03-01
157   2016-03-08
158   2016-03-15
159   2016-03-16
160   2016-03-02
161   2016-03-03
162   2016-03-04
163   2016-03-04
164   2016-03-07
165   2016-03-14
166   2016-03-21
167   2016-03-22
168   2016-03-24
169   2016-03-24
170   2016-03-25
171   2016-03-25
172   2016-03-28
173   2016-03-29
174   2016-03-30
175   2016-03-28
176   2016-03-28
177   2016-03-29
178   2016-03-30
179   2016-03-30
180   2016-03-17
181   2016-03-18
182   2016-03-25
183   2016-03-28
184   2016-04-06
185   2016-04-13
186   2016-04-12
187   2016-04-13
188   2016-04-14
189   2016-04-15
190   2016-04-15
191   2016-04-06
192   2016-04-07
193   2016-04-08
194   2016-04-08
195   2016-04-22
196   2016-04-29
197   2016-04-29
198   2016-04-26
199   2016-04-27
200   2016-04-27
201   2016-04-28
202   2016-04-08
203   2016-04-04
204   2016-05-04
205   2016-05-05
206   2016-05-02
207   2016-05-03
208   2016-05-03
209   2016-05-11
210   2016-05-09
211   2016-05-10
212   2016-05-04
213   2016-05-11
214   2016-05-18
215   2016-05-25
216   2016-05-25
217   2016-05-24
218   2016-05-11
219   2016-05-27
220   2016-06-06
221   2016-06-13
222   2016-06-14
223   2016-06-16
224   2016-06-17
225   2016-06-13
226   2016-06-20
227   2016-06-27
228   2016-06-29
229   2016-06-03
230   2016-06-07
231   2016-06-08
232   2016-06-09
233   2016-06-10
234   2016-06-20
235   2016-06-30
236   2016-07-05
237   2016-07-06
238   2016-07-08
239   2016-07-08
240   2016-07-12
241   2016-07-14
242   2016-07-15
243   2016-07-18
244   2016-07-19
245   2016-07-18
246   2016-07-19
247   2016-07-20
248   2016-07-21
249   2016-07-11
250   2016-07-14
251   2016-07-21
252   2016-08-04
253   2016-08-11
254   2016-08-07
255   2016-08-08
256   2016-08-10
257   2016-08-10
258   2016-08-11
259   2016-08-08
260   2016-08-09
261   2016-08-10
262   2016-08-10
263   2016-08-10
264   2016-08-14
265   2016-08-15
266   2016-08-17
267   2016-08-24
268   2016-08-08
269   2016-08-30
270   2016-09-05
271   2016-09-09
272   2016-09-07
273   2016-09-08
274   2016-09-12
275   2016-09-13
276   2016-09-13
277   2016-09-13
278   2016-09-14
279   2016-09-14
280   2016-09-15
281   2016-09-16
282   2016-09-16
283   2016-09-14
284   2016-09-15
285   2016-09-15
286   2016-09-16
287   2016-09-26
288   2016-09-26
289   2016-10-05
290   2016-10-05
291   2016-10-05
292   2016-10-06
293   2016-10-06
294   2016-10-06
295   2016-10-12
296   2016-10-12
297   2016-10-12
298   2016-10-14
299   2016-10-14
300   2016-10-14
301   2016-10-15
302   2016-10-16
303   2016-10-16
304   2016-10-19
305   2016-10-19
306   2016-10-20
307   2016-10-20
308   2016-10-22
309   2016-10-22
310   2016-10-26
311   2016-10-27
312   2016-10-27
313   2016-10-27
314   2016-10-28
315   2016-10-28
316   2016-10-29
317   2016-11-07
318   2016-11-07
319   2016-11-08
320   2016-11-11
321   2016-11-14
322   2016-11-14
323   2016-11-14
324   2016-11-14
325   2016-11-15
326   2016-11-16
327   2016-11-16
328   2016-11-17
329   2016-11-17
330   2016-11-18
331   2016-11-18
332   2016-11-21
333   2016-11-22
334   2016-11-23
335   2016-11-25
336   2016-11-25
337   2016-11-29
338   2016-11-24
339   2016-12-05
340   2016-12-05
341   2016-12-05
342   2016-12-05
343   2016-12-06
344   2016-12-09
345   2016-12-15
346   2016-12-15
347   2016-12-16
348   2016-12-20
349   2016-12-20
350   2016-12-22
351   2016-12-23
352   2016-12-20
353   2016-12-20
354   2016-12-21
355   2016-12-19
356   2016-12-19
357   2016-12-19
358   2017-01-04
359   2017-01-09
360   2017-01-09
361   2017-01-03
362   2017-01-03
363   2017-01-09
364   2017-01-11
365   2017-01-16
366   2017-01-16
367   2017-01-25
368   2017-01-27
369   2017-02-07
370   2017-02-01
371   2017-02-01
372   2017-02-03
373   2017-02-10
374   2017-02-17
375   2017-02-13
376   2017-02-15
377   2017-02-16
378   2017-02-16
379   2017-02-17
380   2017-02-13
381   2017-02-13
382   2017-02-21
383   2017-02-21
384   2017-02-22
385   2017-02-22
386   2017-02-24
387   2017-02-24
388   2017-02-22
389   2017-02-24
390   2017-03-07
391   2017-03-08
392   2017-03-10
393   2017-03-10
394   2017-03-13
395   2017-03-13
396   2017-03-14
397   2017-03-14
398   2017-03-20
399   2017-03-22
400   2017-03-22
401   2017-03-23
402   2017-03-24
403   2017-03-28
404   2017-03-29
405   2017-03-30
406   2017-03-30
407   2017-03-30
408   2017-03-31
409   2017-03-31
410   2017-03-27
411   2017-03-28
412   2017-04-05
413   2017-04-07
414   2017-04-07
415   2017-04-10
416   2017-04-10
417   2017-04-12
418   2017-04-12
419   2017-04-17
420   2017-04-19
421   2017-04-28
422   2017-04-28
423   2017-04-24
424   2017-04-26
425   2017-05-01
426   2017-05-03
427   2017-05-08
428   2017-05-10
429   2017-05-10
430   2017-05-11
431   2017-05-12
432   2017-05-15
433   2017-05-15
434   2017-05-17
435   2017-05-17
436   2017-05-19
437   2017-05-22
438   2017-05-22
439   2017-05-29
440   2017-05-31
441   2017-06-05
442   2017-06-05
443   2017-06-06
444   2017-06-08
445   2017-06-09
446   2017-06-09
447   2017-06-12
448   2017-06-12
449   2017-06-13
450   2017-06-19
451   2017-06-20
452   2017-06-26
453   2017-06-28
454   2017-06-28
455   2017-06-28
456   2017-06-28
457   2017-06-30
458   2017-06-27
459   2017-06-27
460   2017-07-06
461   2017-07-06
462   2017-07-07
463   2017-07-10
464   2017-07-14
465   2017-07-14
466   2017-07-17
467   2017-07-18
468   2017-07-24
469   2017-07-24
470   2017-07-25
471   2017-07-25
472   2017-07-25
473   2017-07-28
474   2017-07-28
475   2017-07-24
476   2017-07-24
477   2017-07-25
478   2017-07-27
479   2017-07-27
480   2017-08-03
481   2017-08-07
482   2017-08-08
483   2017-08-08
484   2017-08-08
485   2017-08-08
486   2017-08-10
487   2017-08-14
488   2017-08-15
489   2017-08-17
490   2017-08-22
491   2017-08-22
492   2017-08-22
493   2017-08-24
494   2017-08-28
495   2017-09-05
496   2017-09-05
497   2017-09-05
498   2017-09-05
499   2017-09-07
500   2017-09-08
501   2017-09-08
502   2017-09-11
503   2017-09-13
504   2017-09-18
505   2017-09-19
506   2017-09-26
507   2017-10-05
508   2017-10-05
509   2017-10-06
510   2017-10-11
511   2017-10-11
512   2017-10-17
513   2017-10-19
514   2017-10-20
515   2017-10-24
516   2017-10-24
517   2017-10-24
518   2017-10-24
519   2017-10-24
520   2017-10-25
521   2017-10-25
522   2017-10-25
523   2017-10-26
524   2017-10-26
525   2017-10-27
526   2017-10-27
527   2017-10-29
528   2017-10-29
529   2017-10-29
530   2017-10-29
531   2017-10-31
532   2017-11-07
533   2017-11-08
534   2017-11-08
535   2017-11-10
536   2017-11-14
537   2017-11-15
538   2017-11-17
539   2017-11-17
540   2017-11-21
541   2017-11-22
542   2017-11-23
543   2017-11-23
544   2017-11-27
545   2017-11-27
546   2017-11-28
547   2017-11-28
548   2017-11-28
549   2017-11-29
550   2017-11-30
551   2017-11-30
552   2017-11-24
553   2017-11-24
554   2017-11-27
555   2017-12-05
556   2017-12-06
557   2017-12-06
558   2017-12-08
559   2017-12-08
560   2017-12-13
561   2017-12-14
562   2017-12-15
563   2017-12-15
564   2017-12-18
565   2017-12-19
566   2017-12-19
567   2017-12-21
568   2017-12-18
569   2017-12-19
570   2018-01-01
571   2018-01-04
572   2018-01-04
573   2018-01-05
574   2018-01-08
575   2018-01-10
576   2018-01-11
577   2018-01-12
578   2018-01-15
579   2018-01-16
580   2018-01-17
581   2018-01-17
582   2018-01-17
583   2018-01-18
584   2018-01-26
585   2018-02-06
586   2018-02-06
587   2018-02-07
588   2018-02-07
589   2018-02-08
590   2018-02-08
591   2018-02-08
592   2018-02-09
593   2018-02-09
594   2018-02-12
595   2018-02-12
596   2018-02-13
597   2018-02-14
598   2018-02-15
599   2018-02-15
600   2018-02-15
601   2018-02-16
602   2018-02-16
603   2018-02-21
604   2018-02-21
605   2018-02-21
606   2018-02-22
607   2018-02-23
608   2018-02-26
609   2018-02-26
610   2018-02-26
611   2018-02-26
612   2018-02-27
613   2018-02-27
614   2018-02-27
615   2018-02-28
616   2018-02-22
617   2018-02-23
618   2018-03-05
619   2018-03-05
620   2018-03-06
621   2018-03-06
622   2018-03-06
623   2018-03-07
624   2018-03-08
625   2018-03-08
626   2018-03-08
627   2018-03-09
628   2018-03-12
629   2018-03-12
630   2018-03-13
631   2018-03-14
632   2018-03-15
633   2018-03-16
634   2018-03-19
635   2018-03-19
636   2018-03-19
637   2018-03-19
638   2018-03-20
639   2018-03-21
640   2018-03-21
641   2018-03-21
642   2018-03-22
643   2018-03-22
644   2018-03-23
645   2018-03-23
646   2018-03-27
647   2018-03-28
648   2018-03-28
649   2018-03-28
650   2018-03-29
651   2018-03-26
652   2018-03-26
653   2018-03-28
654   2018-04-02
655   2018-04-02
656   2018-04-03
657   2018-04-04
658   2018-04-05
659   2018-04-06
660   2018-04-09
661   2018-04-10
662   2018-04-10
663   2018-04-10
664   2018-04-11
665   2018-04-13
666   2018-04-13
667   2018-04-16
668   2018-04-17
669   2018-04-20
670   2018-04-24
671   2018-04-26
672   2018-04-26
673   2018-04-27
674   2018-05-07
675   2018-05-09
676   2018-05-09
677   2018-05-09
678   2018-05-09
679   2018-05-10
680   2018-05-10
681   2018-05-10
682   2018-05-11
683   2018-05-11
684   2018-05-11
685   2018-05-14
686   2018-05-15
687   2018-05-15
688   2018-05-15
689   2018-05-16
690   2018-05-16
691   2018-05-18
692   2018-05-21
693   2018-05-21
694   2018-05-23
695   2018-05-23
696   2018-05-23
697   2018-05-24
698   2018-05-24
699   2018-05-31
Name: Date, dtype: datetime64[ns]

#### **Extracting Month Value**

In [555]:
df_reason_mode.Date[0]

Timestamp('2015-07-07 00:00:00')

In [556]:
## Extracting Year Value
print(df_reason_mode.Date[0].year)

## Extracting Month Value
print(df_reason_mode.Date[0].month)

## Extracting Day Value
print(df_reason_mode.Date[0].weekday())

2015
7
1

In [557]:
day_list = []
for i in range(df_reason_mode.shape[0]):
    day_list.append(df_reason_mode.Date[i].weekday())
df_reason_mode['Day of the Week'] = day_list

In [558]:
## Creating Day Value column
def date_to_weekday(date_value):
    return date_value.weekday()
df_reason_mode['Date'].apply(date_to_weekday)

## Creating a Month Value column 
months_list = []
for i in range(df_reason_mode.shape[0]):
    months_list.append(df_reason_mode.Date[i].month)
df_reason_mode['Month Value'] = months_list

## Creating a Year Value column
year_list =  []
for i in range(df_reason_mode.shape[0]):
    year_list.append(df_reason_mode.Date[i].year)
df_reason_mode['Year Value'] = year_list

df_reason_mode.head(20)

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Day of the Week,Month Value,Year Value
0,0,0,0,1,2015-07-07,289,36,33,239.554,30,1,2,1,4,1,7,2015
1,0,0,0,0,2015-07-14,118,13,50,239.554,31,1,1,0,0,1,7,2015
2,0,0,0,1,2015-07-15,179,51,38,239.554,31,1,0,0,2,2,7,2015
3,1,0,0,0,2015-07-16,279,5,39,239.554,24,1,2,0,4,3,7,2015
4,0,0,0,1,2015-07-23,289,36,33,239.554,30,1,2,1,2,3,7,2015
5,0,0,0,1,2015-07-10,179,51,38,239.554,31,1,0,0,2,4,7,2015
6,0,0,0,1,2015-07-17,361,52,28,239.554,27,1,1,4,8,4,7,2015
7,0,0,0,1,2015-07-24,260,50,36,239.554,23,1,4,0,4,4,7,2015
8,0,0,1,0,2015-07-06,155,12,34,239.554,25,1,2,0,40,0,7,2015
9,0,0,0,1,2015-07-13,235,11,37,239.554,29,3,1,1,8,0,7,2015
10,1,0,0,0,2015-07-20,260,50,36,239.554,23,1,4,0,8,0,7,2015
11,1,0,0,0,2015-07-14,260,50,36,239.554,23,1,4,0,8,1,7,2015
12,1,0,0,0,2015-07-15,260,50,36,239.554,23,1,4,0,8,2,7,2015
13,1,0,0,0,2015-07-15,179,51,38,239.554,31,1,0,0,1,2,7,2015
14,0,0,0,1,2015-07-15,179,51,38,239.554,31,1,0,0,4,2,7,2015
15,1,0,0,0,2015-07-17,246,25,41,239.554,23,1,0,0,8,4,7,2015
16,0,0,0,1,2015-07-17,179,51,38,239.554,31,1,0,0,2,4,7,2015
17,0,0,1,0,2015-07-27,179,51,38,239.554,31,1,0,0,8,0,7,2015
18,1,0,0,0,2015-07-30,189,29,33,239.554,25,1,2,2,8,3,7,2015
19,0,0,0,1,2015-08-05,248,25,47,205.917,32,1,2,1,2,2,8,2015

In [559]:
df_reason_mode.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Date',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Day of the Week',
       'Month Value', 'Year Value'], dtype=object)

In [560]:
new_columns = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Day of the Week',
               'Month Value','Transportation Expense', 'Distance to Work', 'Age',
               'Daily Work Load Average', 'Body Mass Index', 'Education',
               'Children', 'Pets', 'Absenteeism Time in Hours']

df_reason_mode = df_reason_mode[new_columns]
df_reason_mode.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Day of the Week,Month Value,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,1,7,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,1,7,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,2,7,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,3,7,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,3,7,289,36,33,239.554,30,1,2,1,2

#### **The The Data Types of the Next Five Relevant Columns**

In [561]:
print(type(df_reason_mode['Transportation Expense'][0]))
print(type(df_reason_mode['Distance to Work'][0]))
print(type(df_reason_mode['Age'][0]))
print(type(df_reason_mode['Daily Work Load Average'][0]))
print(type(df_reason_mode['Body Mass Index'][0]))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'numpy.int64'>

#### **'Education', 'Children', 'Pets'**

In [562]:
for i in df_reason_mode.loc[:,'Education':'Pets']:
    ## Unique values
    print(f"Unique Values in {i}:\n{df_reason_mode[i].unique()}")
    ## Number of unique values
    print(f"Number of Unique Values in {i}:\n{df_reason_mode[i].nunique()}")
    ## Unique Value Count
    print(f"Unique Value Counts for {i}:\n{df_reason_mode[i].value_counts()}\n")

Unique Values in Education:
[1 3 2 4]
Number of Unique Values in Education:
4
Unique Value Counts for Education:
Education
1    583
3     73
2     40
4      4
Name: count, dtype: int64

Unique Values in Children:
[2 1 0 4 3]
Number of Unique Values in Children:
5
Unique Value Counts for Children:
Children
0    285
1    213
2    146
4     42
3     14
Name: count, dtype: int64

Unique Values in Pets:
[1 0 4 2 5 8]
Number of Unique Values in Pets:
6
Unique Value Counts for Pets:
Pets
0    439
1    132
2     92
4     29
5      5
8      3
Name: count, dtype: int64

In [563]:
## Generating 2 categories for Unique Value Counts for [Education]: {1, 2, 3, 4. 1:0 and 2,3,4:1}
df_reason_mode['Education'] = df_reason_mode.Education.map({1:0, 2:1, 3:1, 4:1})
print(f"---Education---:\nUnique Values: {df_reason_mode.Education.unique()}\n\nUnique Value Counts:\n{df_reason_mode.Education.value_counts()} ")

---Education---:
Unique Values: [0 1]

Unique Value Counts:
Education
0    583
1    117
Name: count, dtype: int64

#### **Final Checkpoint**

In [564]:
df_cleaned = df_reason_mode.copy()
df_cleaned.head(10)

,Reason_1,Reason_2,Reason_3,Reason_4,Day of the Week,Month Value,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,1,7,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,1,7,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,2,7,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,3,7,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,3,7,289,36,33,239.554,30,0,2,1,2
5,0,0,0,1,4,7,179,51,38,239.554,31,0,0,0,2
6,0,0,0,1,4,7,361,52,28,239.554,27,0,1,4,8
7,0,0,0,1,4,7,260,50,36,239.554,23,0,4,0,4
8,0,0,1,0,0,7,155,12,34,239.554,25,0,2,0,40
9,0,0,0,1,0,7,235,11,37,239.554,29,1,1,1,8